/*
 * LoLClient
 *
 * League of Legends Game Client
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lolgameclient
// BindingAsyncFailureEvent Represents a failed asynchronous operation.
type BindingAsyncFailureEvent struct {
	// Asynchronous operation token
	AsyncToken int32 `json:"asyncToken,omitempty"`
	// Error message
	Error string `json:"error,omitempty"`
}
