/*
 * LoLClient
 *
 * League of Legends Game Client
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lolgameclient
// BindingFullEventHelp Describes an event.
type BindingFullEventHelp struct {
	Description string `json:"description,omitempty"`
	Name string `json:"name,omitempty"`
	NameSpace string `json:"nameSpace,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Type BindingFullTypeIdentifier `json:"type,omitempty"`
}
