/*
 * LoLClient
 *
 * League of Legends Game Client
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lolgameclient
// Color Color
type Color struct {
	A int32 `json:"a,omitempty"`
	B int32 `json:"b,omitempty"`
	G int32 `json:"g,omitempty"`
	R int32 `json:"r,omitempty"`
}
