/*
 * LoLClient
 *
 * League of Legends Game Client
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lolgameclient
// BindingFullFunctionHelp Describes a function.
type BindingFullFunctionHelp struct {
	Arguments []BindingFullArgumentHelp `json:"arguments,omitempty"`
	Async string `json:"async,omitempty"`
	Description string `json:"description,omitempty"`
	Help string `json:"help,omitempty"`
	Name string `json:"name,omitempty"`
	NameSpace string `json:"nameSpace,omitempty"`
	Returns BindingFullTypeIdentifier `json:"returns,omitempty"`
	Tags []string `json:"tags,omitempty"`
	ThreadSafe bool `json:"threadSafe,omitempty"`
}
