/*
 * LoLClient
 *
 * League of Legends Game Client
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Vector4f 4D vector
type Vector4f struct {
	W float32 `json:"w,omitempty"`
	X float32 `json:"x,omitempty"`
	Y float32 `json:"y,omitempty"`
	Z float32 `json:"z,omitempty"`
}
