/*
 * LoLClient
 *
 * League of Legends Game Client
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TeamId Team identification
type TeamId string

// List of TeamID
const (
	ALL TeamId = "ALL"
	UNKNOWN TeamId = "UNKNOWN"
	ORDER TeamId = "ORDER"
	CHAOS TeamId = "CHAOS"
	NEUTRAL TeamId = "NEUTRAL"
)
