/*
 * LoLClient
 *
 * League of Legends Game Client
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lolgameclient
// BindingFullArgumentHelp Describes a function parameter.
type BindingFullArgumentHelp struct {
	Description string `json:"description,omitempty"`
	Name string `json:"name,omitempty"`
	Optional bool `json:"optional,omitempty"`
	Type BindingFullTypeIdentifier `json:"type,omitempty"`
}
