/*
 * LoLClient
 *
 * League of Legends Game Client
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lolgameclient
// BindingFullTypeIdentifier Describes the type of a value.
type BindingFullTypeIdentifier struct {
	ElementType string `json:"elementType,omitempty"`
	Type string `json:"type,omitempty"`
}
