/*
 * LoLClient
 *
 * League of Legends Game Client
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lolgameclient
// BindingCallbackEvent Represents the parameters of a call to a provided callback.
type BindingCallbackEvent struct {
	// ID of the callback being invoked
	Id int32 `json:"id,omitempty"`
	// Callback parameters
	Parameters []map[string]map[string]interface{} `json:"parameters,omitempty"`
}
