/*
 * LoLClient
 *
 * League of Legends Game Client
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lolgameclient
// RemotingPrivilege Well-known privilege levels for bindable functions.
type RemotingPrivilege string

// List of RemotingPrivilege
const (
	NONE RemotingPrivilege = "None"
	USER RemotingPrivilege = "User"
	ADMIN RemotingPrivilege = "Admin"
	LOCAL RemotingPrivilege = "Local"
)
