/*
 * LoLClient
 *
 * League of Legends Game Client
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lolgameclient
// BindingHelpFormat Help format for binding functions and types.
type BindingHelpFormat string

// List of BindingHelpFormat
const (
	FULL BindingHelpFormat = "Full"
	EPYTEXT BindingHelpFormat = "Epytext"
)
