/*
 * LoLClient
 *
 * League of Legends Game Client
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// BindingFullApiHelp Describes the exposed native API.
type BindingFullApiHelp struct {
	Events []BindingFullEventHelp `json:"events,omitempty"`
	Functions []BindingFullFunctionHelp `json:"functions,omitempty"`
	Types []BindingFullTypeHelp `json:"types,omitempty"`
}
