/*
 * LoLClient
 *
 * League of Legends Game Client
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Vector2f 2D vector
type Vector2f struct {
	X float32 `json:"x,omitempty"`
	Y float32 `json:"y,omitempty"`
}
