/*
 * LoLClient
 *
 * League of Legends Game Client
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// BindingAsyncCancelEvent Represents a cancelled asynchronous operation.
type BindingAsyncCancelEvent struct {
	// Asynchronous operation token
	AsyncToken int32 `json:"asyncToken,omitempty"`
}
