/*
 * LoLClient
 *
 * League of Legends Game Client
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lolgameclient
// RemotingSerializedFormat Serialization format for remoting requests and results.
type RemotingSerializedFormat string

// List of RemotingSerializedFormat
const (
	JSON RemotingSerializedFormat = "JSON"
	YAML RemotingSerializedFormat = "YAML"
	MSG_PACK RemotingSerializedFormat = "MsgPack"
)
