/*
 * LoLClient
 *
 * League of Legends Game Client
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// RemotingHelpFormat Help format for remoting functions and types.
type RemotingHelpFormat string

// List of RemotingHelpFormat
const (
	FULL RemotingHelpFormat = "Full"
	EPYTEXT RemotingHelpFormat = "Epytext"
	BRIEF RemotingHelpFormat = "Brief"
	CONSOLE RemotingHelpFormat = "Console"
)
