/*
 * LoLClient
 *
 * League of Legends Game Client
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AbilityResource Ability Resource
type AbilityResource string

// List of AbilityResource
const (
	MANA AbilityResource = "MANA"
	ENERGY AbilityResource = "ENERGY"
	NONE AbilityResource = "NONE"
	SHIELD AbilityResource = "SHIELD"
	BATTLEFURY AbilityResource = "BATTLEFURY"
	DRAGONFURY AbilityResource = "DRAGONFURY"
	RAGE AbilityResource = "RAGE"
	HEAT AbilityResource = "HEAT"
	GNARFURY AbilityResource = "GNARFURY"
	FEROCITY AbilityResource = "FEROCITY"
	BLOODWELL AbilityResource = "BLOODWELL"
	WIND AbilityResource = "WIND"
	AMMO AbilityResource = "AMMO"
	OTHER AbilityResource = "OTHER"
	MAX AbilityResource = "MAX"
)
