/*
 * LoLClient
 *
 * League of Legends Game Client
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// BindingFullTypeHelp Describes a struct or enum type.
type BindingFullTypeHelp struct {
	Description string `json:"description,omitempty"`
	Fields []BindingFullFieldHelp `json:"fields,omitempty"`
	Name string `json:"name,omitempty"`
	NameSpace string `json:"nameSpace,omitempty"`
	Size int32 `json:"size,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Values []BindingFullEnumValueHelp `json:"values,omitempty"`
}
