/*
 * LoLClient
 *
 * League of Legends Game Client
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// BindingAsyncState Possible states of an asynchronous operation.
type BindingAsyncState string

// List of BindingAsyncState
const (
	NONE BindingAsyncState = "None"
	RUNNING BindingAsyncState = "Running"
	CANCELLING BindingAsyncState = "Cancelling"
	CANCELLED BindingAsyncState = "Cancelled"
	SUCCEEDED BindingAsyncState = "Succeeded"
	FAILED BindingAsyncState = "Failed"
)
