/*
 * LoLClient
 *
 * League of Legends Game Client
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// BindingFullEnumValueHelp Describes an enumerator.
type BindingFullEnumValueHelp struct {
	Description string `json:"description,omitempty"`
	Name string `json:"name,omitempty"`
	Value int32 `json:"value,omitempty"`
}
