/*
 * LoLClient
 *
 * League of Legends Game Client
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// BindingGenericAsyncEvent Represents generic data for an asynchronous event.
type BindingGenericAsyncEvent struct {
	// Asynchronous operation token
	AsyncToken int32 `json:"asyncToken,omitempty"`
	// Event data
	Data map[string]map[string]interface{} `json:"data,omitempty"`
}
